#! /bin/sh

sxhkd -c "/home/SP649/.config/sxhkd/sxhkdrc" &

polybar -r bspwm1 &
polybar -r bspwm2 &

#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP-1 -d 1 3 5 7 9
bspc monitor HDMI-1-0 -d 2 4 6 8 10

bspc config border_width         4
bspc config window_gap          4

bspc config normal_border_color \#616161
bspc config active_border_color \#616161
bspc config focused_border_color \#85678f
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true